2023-08-30 14:40:55,565 - worker_process - INFO - Worker_process started.
2023-08-30 14:40:55,808 - Cell - INFO - site-1.35dbe7ce-37b3-4d18-865d-83ac0dda1c13: created backbone internal connector to tcp://localhost:1078 on parent
2023-08-30 14:40:55,831 - Cell - INFO - site-1.35dbe7ce-37b3-4d18-865d-83ac0dda1c13: created backbone external connector to grpc://192.168.100.3:8102
2023-08-30 14:40:55,831 - nvflare.fuel.f3.sfm.conn_manager - INFO - Connector [CH00001 ACTIVE tcp://localhost:1078] is starting
2023-08-30 14:40:55,832 - nvflare.fuel.f3.sfm.conn_manager - INFO - Connector [CH00002 ACTIVE grpc://192.168.100.3:8102] is starting
2023-08-30 14:40:55,832 - FederatedClient - INFO - Wait for client_runner to be created.
2023-08-30 14:40:55,833 - FederatedClient - INFO - Got client_runner after 0.00016570091247558594 seconds
2023-08-30 14:40:55,833 - FederatedClient - INFO - Got the new primary SP: grpc://192.168.100.3:8102
2023-08-30 14:40:55,842 - ClientRunner - INFO - [identity=site-1, run=35dbe7ce-37b3-4d18-865d-83ac0dda1c13]: client runner started
2023-08-30 14:40:55,868 - Communicator - INFO - Received from secure_project server  (1114733 Bytes). getTask: train time: 0.016262531280517578 seconds
2023-08-30 14:40:55,869 - FederatedClient - INFO - pull_task completed. Task name:train Status:True 
2023-08-30 14:40:55,869 - ClientRunner - INFO - [identity=site-1, run=35dbe7ce-37b3-4d18-865d-83ac0dda1c13, peer=secure_project, peer_run=35dbe7ce-37b3-4d18-865d-83ac0dda1c13]: got task assignment: name=train, id=91d7f499-025e-48d2-835b-8b6af6f8c5f0
2023-08-30 14:40:55,870 - ClientRunner - INFO - [identity=site-1, run=35dbe7ce-37b3-4d18-865d-83ac0dda1c13, peer=secure_project, peer_run=35dbe7ce-37b3-4d18-865d-83ac0dda1c13, task_name=train, task_id=91d7f499-025e-48d2-835b-8b6af6f8c5f0]: invoking task executor LearnerExecutor
2023-08-30 14:40:55,870 - LearnerExecutor - INFO - [identity=site-1, run=35dbe7ce-37b3-4d18-865d-83ac0dda1c13, peer=secure_project, peer_run=35dbe7ce-37b3-4d18-865d-83ac0dda1c13, task_name=train, task_id=91d7f499-025e-48d2-835b-8b6af6f8c5f0]: Client trainer got task: train
2023-08-30 14:40:55,870 - MNISTLearner - INFO - [identity=site-1, run=35dbe7ce-37b3-4d18-865d-83ac0dda1c13, peer=secure_project, peer_run=35dbe7ce-37b3-4d18-865d-83ac0dda1c13, task_name=train, task_id=91d7f499-025e-48d2-835b-8b6af6f8c5f0]: Client site-1 initialized at 
 /home/aienode1/NVFlare/sound_cls/mnist-real-world/workspaces/secure_workspace/site-1/startup/../35dbe7ce-37b3-4d18-865d-83ac0dda1c13/app_site-1 
 with args: Namespace(workspace='/home/aienode1/NVFlare/sound_cls/mnist-real-world/workspaces/secure_workspace/site-1/startup/..', startup='/home/aienode1/NVFlare/sound_cls/mnist-real-world/workspaces/secure_workspace/site-1/startup/../startup', token='46f86140-8de3-4521-841f-6972de9e2a26', ssid='ebc6125d-0a56-4688-9b08-355fe9e4d61a', job_id='35dbe7ce-37b3-4d18-865d-83ac0dda1c13', client_name='site-1', sp_target='192.168.100.3:8102', parent_url='tcp://localhost:1078', fed_client='fed_client.json', set=['secure_train=true', 'uid=site-1', 'org=nvidia', 'config_folder=config', 'print_conf=True'], local_rank=0, train_config='config/config_train.json', client_config='config/config_fed_client.json', config_folder='config', env='config/environment.json')
2023-08-30 14:40:57,323 - ClientRunner - ERROR - [identity=site-1, run=35dbe7ce-37b3-4d18-865d-83ac0dda1c13, peer=secure_project, peer_run=35dbe7ce-37b3-4d18-865d-83ac0dda1c13, task_name=train, task_id=91d7f499-025e-48d2-835b-8b6af6f8c5f0]: Processing error from executor LearnerExecutor: ValueError: num_samples should be a positive integer value, but got num_samples=0
2023-08-30 14:40:57,325 - ClientRunner - ERROR - Traceback (most recent call last):
  File "/home/aienode1/anaconda3/lib/python3.10/site-packages/nvflare/private/fed/client/client_runner.py", line 254, in _process_task
    reply = executor.execute(task.name, task.data, fl_ctx, self.task_abort_signal)
  File "/home/aienode1/anaconda3/lib/python3.10/site-packages/nvflare/app_common/executors/learner_executor.py", line 86, in execute
    return self.train(shareable, fl_ctx, abort_signal)
  File "/home/aienode1/anaconda3/lib/python3.10/site-packages/nvflare/app_common/executors/learner_executor.py", line 99, in train
    validate_result: Shareable = self.learner.validate(shareable, fl_ctx, abort_signal)
  File "/home/aienode1/NVFlare/sound_cls/pt/learners/sound_learner.py", line 357, in validate
    self._create_datasets(fl_ctx)
  File "/home/aienode1/NVFlare/sound_cls/pt/learners/sound_learner.py", line 165, in _create_datasets
    self.train_loader = self.train_datamgr.get_loader(self.transform_train, batch_size=self.batch_size, shuffle=True, num_workers=self.num_workers)
  File "/home/aienode1/NVFlare/sound_cls/pt/utils/data_manager.py", line 38, in get_loader
    return data.DataLoader(dataset=dataset, shuffle=shuffle, batch_size=batch_size, num_workers=num_workers, drop_last=True, collate_fn=self.pad_seq)
  File "/home/aienode1/anaconda3/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 351, in __init__
    sampler = RandomSampler(dataset, generator=generator)  # type: ignore[arg-type]
  File "/home/aienode1/anaconda3/lib/python3.10/site-packages/torch/utils/data/sampler.py", line 107, in __init__
    raise ValueError("num_samples should be a positive integer "
ValueError: num_samples should be a positive integer value, but got num_samples=0

2023-08-30 14:40:57,326 - FederatedClient - INFO - Starting to push execute result.
2023-08-30 14:40:57,330 - Communicator - INFO -  SubmitUpdate size: 575 Bytes. time: 0.0031890869140625 seconds
2023-08-30 14:40:57,331 - ClientRunner - INFO - [identity=site-1, run=35dbe7ce-37b3-4d18-865d-83ac0dda1c13, peer=secure_project, peer_run=35dbe7ce-37b3-4d18-865d-83ac0dda1c13, task_name=train, task_id=91d7f499-025e-48d2-835b-8b6af6f8c5f0]: result sent to server for task: name=train, id=91d7f499-025e-48d2-835b-8b6af6f8c5f0
2023-08-30 14:40:58,081 - ClientRunner - INFO - [identity=site-1, run=35dbe7ce-37b3-4d18-865d-83ac0dda1c13, peer=secure_project, peer_run=35dbe7ce-37b3-4d18-865d-83ac0dda1c13]: received aux request from Server to end current RUN
2023-08-30 14:40:58,082 - ClientRunner - INFO - [identity=site-1, run=35dbe7ce-37b3-4d18-865d-83ac0dda1c13]: ABORT (RUN) command received
2023-08-30 14:40:58,083 - ClientRunner - INFO - [identity=site-1, run=35dbe7ce-37b3-4d18-865d-83ac0dda1c13]: ABORT (RUN) requests end run events sequence
2023-08-30 14:40:58,083 - ClientRunner - INFO - [identity=site-1, run=35dbe7ce-37b3-4d18-865d-83ac0dda1c13]: ABOUT_TO_END_RUN fired
2023-08-30 14:40:58,084 - ClientRunner - INFO - [identity=site-1, run=35dbe7ce-37b3-4d18-865d-83ac0dda1c13]: END_RUN fired
2023-08-30 14:40:59,333 - ClientRunner - INFO - [identity=site-1, run=35dbe7ce-37b3-4d18-865d-83ac0dda1c13]: run method requests end run events sequence
2023-08-30 14:40:59,344 - FederatedClient - INFO - Shutting down client run: site-1
2023-08-30 14:41:01,173 - MPM - INFO - MPM: Good Bye!
