2023-08-30 15:18:05,314 - worker_process - INFO - Worker_process started.
2023-08-30 15:18:05,572 - Cell - INFO - site-1.f16e802a-521f-462c-9a25-412ca252206c: created backbone internal connector to tcp://localhost:29726 on parent
2023-08-30 15:18:05,598 - Cell - INFO - site-1.f16e802a-521f-462c-9a25-412ca252206c: created backbone external connector to grpc://192.168.100.3:8102
2023-08-30 15:18:05,598 - nvflare.fuel.f3.sfm.conn_manager - INFO - Connector [CH00001 ACTIVE tcp://localhost:29726] is starting
2023-08-30 15:18:05,598 - nvflare.fuel.f3.sfm.conn_manager - INFO - Connector [CH00002 ACTIVE grpc://192.168.100.3:8102] is starting
2023-08-30 15:18:05,599 - FederatedClient - INFO - Wait for client_runner to be created.
2023-08-30 15:18:05,599 - FederatedClient - INFO - Got client_runner after 0.00043964385986328125 seconds
2023-08-30 15:18:05,600 - FederatedClient - INFO - Got the new primary SP: grpc://192.168.100.3:8102
2023-08-30 15:18:05,610 - ClientRunner - INFO - [identity=site-1, run=f16e802a-521f-462c-9a25-412ca252206c]: client runner started
2023-08-30 15:18:05,634 - Communicator - INFO - Received from secure_project server  (1114733 Bytes). getTask: train time: 0.01650857925415039 seconds
2023-08-30 15:18:05,635 - FederatedClient - INFO - pull_task completed. Task name:train Status:True 
2023-08-30 15:18:05,635 - ClientRunner - INFO - [identity=site-1, run=f16e802a-521f-462c-9a25-412ca252206c, peer=secure_project, peer_run=f16e802a-521f-462c-9a25-412ca252206c]: got task assignment: name=train, id=2c0a4aa7-82ec-441b-995b-9a2469b5632a
2023-08-30 15:18:05,635 - ClientRunner - INFO - [identity=site-1, run=f16e802a-521f-462c-9a25-412ca252206c, peer=secure_project, peer_run=f16e802a-521f-462c-9a25-412ca252206c, task_name=train, task_id=2c0a4aa7-82ec-441b-995b-9a2469b5632a]: invoking task executor LearnerExecutor
2023-08-30 15:18:05,636 - LearnerExecutor - INFO - [identity=site-1, run=f16e802a-521f-462c-9a25-412ca252206c, peer=secure_project, peer_run=f16e802a-521f-462c-9a25-412ca252206c, task_name=train, task_id=2c0a4aa7-82ec-441b-995b-9a2469b5632a]: Client trainer got task: train
2023-08-30 15:18:05,636 - MNISTLearner - INFO - [identity=site-1, run=f16e802a-521f-462c-9a25-412ca252206c, peer=secure_project, peer_run=f16e802a-521f-462c-9a25-412ca252206c, task_name=train, task_id=2c0a4aa7-82ec-441b-995b-9a2469b5632a]: Client site-1 initialized at 
 /home/aienode1/NVFlare/sound_cls/mnist-real-world/workspaces/secure_workspace/site-1/startup/../f16e802a-521f-462c-9a25-412ca252206c/app_site-1 
 with args: Namespace(workspace='/home/aienode1/NVFlare/sound_cls/mnist-real-world/workspaces/secure_workspace/site-1/startup/..', startup='/home/aienode1/NVFlare/sound_cls/mnist-real-world/workspaces/secure_workspace/site-1/startup/../startup', token='d2c82c93-15f6-4e9e-8318-e0e19a0309fe', ssid='ebc6125d-0a56-4688-9b08-355fe9e4d61a', job_id='f16e802a-521f-462c-9a25-412ca252206c', client_name='site-1', sp_target='192.168.100.3:8102', parent_url='tcp://localhost:29726', fed_client='fed_client.json', set=['secure_train=true', 'uid=site-1', 'org=nvidia', 'config_folder=config', 'print_conf=True'], local_rank=0, train_config='config/config_train.json', client_config='config/config_fed_client.json', config_folder='config', env='config/environment.json')
2023-08-30 15:18:06,945 - ClientRunner - ERROR - [identity=site-1, run=f16e802a-521f-462c-9a25-412ca252206c, peer=secure_project, peer_run=f16e802a-521f-462c-9a25-412ca252206c, task_name=train, task_id=2c0a4aa7-82ec-441b-995b-9a2469b5632a]: Processing error from executor LearnerExecutor: ValueError: num_samples should be a positive integer value, but got num_samples=0
2023-08-30 15:18:06,945 - ClientRunner - ERROR - Traceback (most recent call last):
  File "/home/aienode1/anaconda3/lib/python3.10/site-packages/nvflare/private/fed/client/client_runner.py", line 254, in _process_task
    reply = executor.execute(task.name, task.data, fl_ctx, self.task_abort_signal)
  File "/home/aienode1/anaconda3/lib/python3.10/site-packages/nvflare/app_common/executors/learner_executor.py", line 86, in execute
    return self.train(shareable, fl_ctx, abort_signal)
  File "/home/aienode1/anaconda3/lib/python3.10/site-packages/nvflare/app_common/executors/learner_executor.py", line 99, in train
    validate_result: Shareable = self.learner.validate(shareable, fl_ctx, abort_signal)
  File "/home/aienode1/NVFlare/sound_cls/pt/learners/sound_learner.py", line 357, in validate
    self._create_datasets(fl_ctx)
  File "/home/aienode1/NVFlare/sound_cls/pt/learners/sound_learner.py", line 165, in _create_datasets
    self.train_loader = self.train_datamgr.get_loader(self.transform_train, batch_size=self.batch_size, shuffle=True, num_workers=self.num_workers, train=True)
  File "/home/aienode1/NVFlare/sound_cls/pt/utils/data_manager.py", line 36, in get_loader
    loader = data.DataLoader(dataset=dataset, shuffle=shuffle, batch_size=batch_size, num_workers=num_workers, drop_last=True, collate_fn=self.pad_seq)
  File "/home/aienode1/anaconda3/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 351, in __init__
    sampler = RandomSampler(dataset, generator=generator)  # type: ignore[arg-type]
  File "/home/aienode1/anaconda3/lib/python3.10/site-packages/torch/utils/data/sampler.py", line 107, in __init__
    raise ValueError("num_samples should be a positive integer "
ValueError: num_samples should be a positive integer value, but got num_samples=0

2023-08-30 15:18:06,946 - FederatedClient - INFO - Starting to push execute result.
2023-08-30 15:18:06,950 - Communicator - INFO -  SubmitUpdate size: 575 Bytes. time: 0.0032236576080322266 seconds
2023-08-30 15:18:06,950 - ClientRunner - INFO - [identity=site-1, run=f16e802a-521f-462c-9a25-412ca252206c, peer=secure_project, peer_run=f16e802a-521f-462c-9a25-412ca252206c, task_name=train, task_id=2c0a4aa7-82ec-441b-995b-9a2469b5632a]: result sent to server for task: name=train, id=2c0a4aa7-82ec-441b-995b-9a2469b5632a
2023-08-30 15:18:07,564 - ClientRunner - INFO - [identity=site-1, run=f16e802a-521f-462c-9a25-412ca252206c, peer=secure_project, peer_run=f16e802a-521f-462c-9a25-412ca252206c]: received aux request from Server to end current RUN
2023-08-30 15:18:07,564 - ClientRunner - INFO - [identity=site-1, run=f16e802a-521f-462c-9a25-412ca252206c]: ABORT (RUN) command received
2023-08-30 15:18:07,565 - ClientRunner - INFO - [identity=site-1, run=f16e802a-521f-462c-9a25-412ca252206c]: ABORT (RUN) requests end run events sequence
2023-08-30 15:18:07,565 - ClientRunner - INFO - [identity=site-1, run=f16e802a-521f-462c-9a25-412ca252206c]: ABOUT_TO_END_RUN fired
2023-08-30 15:18:07,566 - ClientRunner - INFO - [identity=site-1, run=f16e802a-521f-462c-9a25-412ca252206c]: END_RUN fired
2023-08-30 15:18:08,953 - ClientRunner - INFO - [identity=site-1, run=f16e802a-521f-462c-9a25-412ca252206c]: run method requests end run events sequence
2023-08-30 15:18:08,968 - FederatedClient - INFO - Shutting down client run: site-1
2023-08-30 15:18:10,923 - MPM - INFO - MPM: Good Bye!
